### ISSUE TITLE
arm64 fuzzer crash

### ISSUE THREAD

**Issue by DanilDelegator** [andreafioraldi/frida-fuzzer#12]
Getting the following error when trying to fuzz a function on a arm64 android.

```>> Starting fuzzing loop...
Traceback (most recent call last):
  File "./frida-fuzzer", line 447, in <module>
    script.exports.loop()
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 333, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: Cannot read property 'buf' of undefined
    at Object.exports.next (fuzz/queue.js:46:1)
    at Object.exports.fuzzing_loop (fuzz/index.js:112:1)
    at Object.rpc.exports.loop (fuzz/index.js:127:1)
    at handleRpcMessage (frida/runtime/message-dispatcher.js:49:1)
    at handleMessage (frida/runtime/message-dispatcher.js:29:1)

**Comment by andreafioraldi** [comment]
queue.js:46 is an empty line, are u using the git-master version?
